In [16]:
import pandas as pd

In [17]:
df = pd.read_feather('emotion_data/Dreamer/dreamer_eeg.feather')

In [18]:
df.head()

,AF3,F7,F3,FC5,T7,P7,O1,O2,P8,T8,...,start_at,end_at,clip_id,subject_id,trial_id,valence,arousal,dominance,baseline_id,_record_id
0,4388.205128,4102.564103,4219.487179,4465.128205,4370.769231,4399.487179,4443.076923,4023.076923,4365.128205,4310.256410,...,0,128,0_1,0,0,4,3,2,0_0,_record_0
1,4375.897436,4093.846154,4252.820513,4522.564103,4435.897436,4411.794872,4488.717949,4108.717949,4399.487179,4384.615385,...,0,128,0_1,0,0,4,3,2,0_0,_record_0
2,4378.461538,4091.282051,4230.256410,4488.205128,4370.256410,4402.564103,4461.025641,4077.435897,4378.461538,4328.717949,...,0,128,0_1,0,0,4,3,2,0_0,_record_0
3,4393.846154,4101.025641,4193.333333,4418.974359,4270.256410,4392.307692,4411.282051,3982.564103,4336.410256,4213.333333,...,0,128,0_1,0,0,4,3,2,0_0,_record_0
4,4396.410256,4108.717949,4210.769231,4436.410256,4310.769231,4401.025641,4426.666667,3980.512821,4349.743590,4238.461538,...,0,128,0_1,0,0,4,3,2,0_0,_record_0

In [19]:
df.columns

Index(['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6',
       'F4', 'F8', 'AF4', 'start_at', 'end_at', 'clip_id', 'subject_id',
       'trial_id', 'valence', 'arousal', 'dominance', 'baseline_id',
       '_record_id'],
      dtype='object')

In [20]:
# check lines per subject_id
lines_per_subject = df['subject_id'].value_counts()
print(lines_per_subject)

subject_id
0     477184
12    477184
21    477184
20    477184
19    477184
18    477184
17    477184
16    477184
15    477184
14    477184
13    477184
11    477184
1     477184
10    477184
9     477184
8     477184
7     477184
6     477184
5     477184
4     477184
3     477184
2     477184
22    477184
Name: count, dtype: int64

In [21]:
# check lines per subject_id,clip_id
lines_per_subject_clip = df.groupby(['subject_id', 'clip_id']).size()
print(lines_per_subject_clip)

subject_id  clip_id
0           0_1        128
            0_10       128
            0_100      128
            0_1000     128
            0_1001     128
                      ...
22          22_995     128
            22_996     128
            22_997     128
            22_998     128
            22_999     128
Length: 85744, dtype: int64

In [22]:
print(df.groupby(['trial_id']).size())

trial_id
0      585856
1      385664
2     1024512
3      488704
4      400384
5      559360
6      565248
7     1159936
8      426880
9      197248
10     282624
11     532864
12    1083392
13     500480
14     906752
15     574080
16     753664
17     547584
dtype: int64

In [23]:
pow = pd.read_feather('emotion_data/Dreamer/dreamer_bandpower_frames.feather')

In [24]:
pow.head()

,subject_id,trial_id,clip_id,valence,arousal,dominance,baseline_id,frame_time,AF3_theta,AF3_alpha,...,F8_theta,F8_alpha,F8_betal,F8_betah,F8_gamma,AF4_theta,AF4_alpha,AF4_betal,AF4_betah,AF4_gamma
0,0,0,0_1,4,3,2,0_0,1.000,9.467925,-6.410549,...,20.478514,11.080406,11.412782,11.497604,24.975021,21.502134,11.088606,11.868764,11.217880,25.084810
1,0,0,0_1,4,3,2,0_0,1.125,9.763124,-6.649513,...,20.298668,9.841968,10.803127,12.454153,24.950859,21.890697,9.890903,11.351929,11.901356,25.023884
2,0,0,0_1,4,3,2,0_0,1.250,9.675969,-6.873539,...,20.524620,8.426636,10.166332,12.998399,24.890888,22.233313,8.583714,10.490187,12.336424,24.973133
3,0,0,0_1,4,3,2,0_0,1.375,9.217568,-7.007887,...,20.933418,7.472155,9.929312,13.080668,24.802284,22.513672,8.053120,9.351501,12.495141,24.936750
4,0,0,0_1,4,3,2,0_0,1.500,8.456484,-6.948922,...,21.346714,7.798600,10.260435,12.705102,24.693066,22.729324,8.935076,8.046970,12.440645,24.911997

In [25]:
pow.shape

(679742, 78)

In [30]:
# check lines per subject_id
lines_per_subject = pow['subject_id'].value_counts()
print(lines_per_subject)

subject_id
0     29554
12    29554
21    29554
20    29554
19    29554
18    29554
17    29554
16    29554
15    29554
14    29554
13    29554
11    29554
1     29554
10    29554
9     29554
8     29554
7     29554
6     29554
5     29554
4     29554
3     29554
2     29554
22    29554
Name: count, dtype: int64

In [27]:
print(pow.groupby(['trial_id']).size())

trial_id
0     36271
1     23759
2     63687
3     30199
4     24679
5     34615
6     34983
7     72151
8     26335
9     11983
10    17319
11    32959
12    67367
13    30935
14    56327
15    35535
16    46759
17    33879
dtype: int64

In [28]:
print(pow.groupby(['subject_id', 'clip_id']).size())

subject_id  clip_id
0           0_1        1577
            0_1177     1521
            0_1370     3137
            0_1765     1145
            0_1911      521
                       ...
22          22_333     2769
            22_3560    1473
            22_682     1313
            22_849     1073
            22_986     1505
Length: 414, dtype: int64